workflows:
  android-workflow:
    name: Build Android APK (project in subfolder)
    max_build_duration: 45
    environment:
      vars:
        JAVA_VERSION: "17"
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
    scripts:
      - name: Prepare Gradle wrapper (repo has no wrapper)
        script: |
          cd AIFileTransferApp_OfflineReady
          curl -sLo /tmp/gradle.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q /tmp/gradle.zip -d /tmp
          export PATH="/tmp/gradle-8.7/bin:$PATH"
          gradle --version
          gradle wrapper --gradle-version 8.7

      - name: Build Debug APK
        script: |
          cd AIFileTransferApp_OfflineReady
          ./gradlew --no-daemon assembleDebug

    artifacts:
      - AIFileTransferApp_OfflineReady/app/build/outputs/**/*.apk

    # Uncomment this block to email the APK when build finishes
    # publishing:
    #   email:
    #     recipients:
    #       - your-email@example.com