scripts:
  - name: Build Debug APK (project lives in subfolder)
    script: |
      export PAworkflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      vars:
        JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
      java: 17
      flutter: stable
    scripts:
      - name: Change to project folder
        script: |
          cd AIFileTransferApp_OfflineReady
      - name: Clean project
        script: |
          ./gradlew clean
      - name: Build Debug APK (project is in subfolder with full logs)
        script: |
          ./gradlew assembleDebug --stacktrace --info --debug
    artifacts:
      - AIFileTransferApp_OfflineReady/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
