workflows:
  android-workflow:
    name: Build Android APK (no wrapper)
    max_build_duration: 45
    environment:
      vars:
        JAVA_VERSION: "17"
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
    scripts:
      - name: Download Gradle 8.7 and add to PATH
        script: |
          curl -sLo /tmp/gradle.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q /tmp/gradle.zip -d /tmp
          export PATH="/tmp/gradle-8.7/bin:$PATH"
          gradle --version

      - name: Build Debug APK (project is in subfolder)
        script: |
          export PATH="/tmp/gradle-8.7/bin:$PATH"
          gradle -p AIFileTransferApp_OfflineReady --no-daemon assembleDebug

    artifacts:
      - AIFileTransferApp_OfflineReady/app/build/outputs/**/*.apk
