workflows:
  android-workflow:
    name: Build Android APK (no wrapper, subfolder project)
    max_build_duration: 45

    environment:
      vars:
        JAVA_VERSION: "17"

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    scripts:
      - name: Download Gradle 8.7 and add to PATH
        script: |
          curl -sLo /tmp/gradle.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q /tmp/gradle.zip -d /tmp
          export PATH="/tmp/gradle-8.7/bin:$PATH"
          gradle --version

      - name: Install required Android SDK components
        script: |
          # 👉 Set these to match your app/build.gradle(.kts)
          SDK_PLATFORM="platforms;android-34"   # compileSdk = 34 → android-34
          BUILD_TOOLS="build-tools;34.0.0"      # buildToolsVersion "34.0.0" (omit if not used)

          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "${SDK_PLATFORM}" "${BUILD_TOOLS}" || true
          sdkmanager --list | head -n 50
          echo "Installed SDK components: ${SDK_PLATFORM}, ${BUILD_TOOLS}"

      - name: Build Debug APK (project lives in subfolder)
        script: |
          export PATH="/tmp/gradle-8.7/bin:$PATH"
          gradle -p AIFileTransferApp_OfflineReady --no-daemon assembleDebug

    artifacts:
      - AIFileTransferApp_OfflineReady/app/build/outputs/**/*.apk
